### ISSUE TITLE
create connection to SQL Server Database

### ISSUE THREAD

**Issue by karan0623** [karan0623/EventLink#17]

**Comment by cordasmd** [comment]
Ben and I researched how to create a connection from our Azure SQL Database to our Visual Studio Code. We used the following links below to setup a connection string between our Visual Studio Code and Azure SQL Database. Once we researched the connection, we went into Visual Studio and opened up the Solution Explorer and right clicked on Connected Services.

We selected Azure SQL Database and because the Azure database is created under Ben's UC email and Visual Studio is signed in under Ben's UC email as well, Visual Studio immediately pulled the SQL database instance I already made. From there, we had to add in the connection string and the admin username and password and Visual Studio established the connection. We added a firewall rule to enable the code to communicate with the server.

**Comment by fishbr1001** [comment]
![Image](https://github.com/karan0623/EventLink/assets/139090864/e2d935b3-b80b-4b52-a254-7535ebccd691)



![Image](https://github.com/karan0623/EventLink/assets/139090864/e85d254e-f3ee-47d9-b21b-982e91a12027)



![Image](https://github.com/karan0623/EventLink/assets/139090864/53ad99a8-18b0-4afc-b3ba-3731b93bba6b)

**Comment by fishbr1001** [comment]
Complete. Server works with code and API
